version: "3.8"
services:
  ansible:
    image: itsmedigio/ansible
    hostname: ansible
    tty: true
    volumes:
      - ./shared-folder:/shared-folder
    build:
      context: .
      dockerfile: Dockerfile.ansible
  web:
    hostname: web
    ports:
      - "999:999"
    image: itsmedigio/rhel
    build:
      context: .
      dockerfile: Dockerfile.centos
  db:
    hostname: db
    image: itsmedigio/rhel
    build:
      context: .
      dockerfile: Dockerfile.centos
