version: "3.8"
services:
  ansible:
    image: itsmedigio/ansible
    hostname: ansible
    tty: true
    volumes:
      - ./playgrounds:/playgrounds
    build:
      context: .
      dockerfile: Dockerfile.ansible
  web01:
    hostname: web01
    image: itsmedigio/rhel
    build:
      context: .
      dockerfile: Dockerfile.centos
  web02:
    hostname: web02
    image: itsmedigio/rhel
    build:
      context: .
      dockerfile: Dockerfile.centos
  app01:
    hostname: app01
    image: itsmedigio/rhel
    build:
      context: .
      dockerfile: Dockerfile.centos
  app02:
    hostname: app02
    image: itsmedigio/rhel
    build:
      context: .
      dockerfile: Dockerfile.centos
  crit01:
    hostname: crit01
    image: itsmedigio/rhel
    build:
      context: .
      dockerfile: Dockerfile.centos
  db01:
    hostname: db01
    image: itsmedigio/rhel
    build:
      context: .
      dockerfile: Dockerfile.centos
